@startuml
'https://plantuml.com/class-diagram

class SpringBootApplication
class Configuration
class ComponentScan
class EnableAutoConfiguration

class Component
class Controller
class RestController
class ResponseBody

Component <|-- Controller
Controller <|-- RestController
RestController <|-- ResponseBody
SpringBootApplication *-- Configuration
SpringBootApplication *-- ComponentScan
SpringBootApplication *-- EnableAutoConfiguration

@enduml